# This file is a template, and might need editing before it works on your project.
# Official docker image.
services:
  - docker:stable-dind

stages:
  - build
  - deploy

variables:
  CI_REGISTRY: "docker.io"
  CI_REGISTRY_IMAGE: "beardedio/git-tools"
  CI_REGISTRY_USER: "set-as-secret-variable"
  CI_REGISTRY_PASSWORD: "set-as-secret-variable"

build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_TAG: "latest"
    DOCKER_FILE: "Dockerfile"
  only:
    - master
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export DOCKER_TAG=$(cat version | xargs)
    - docker build --pull --tag "$CI_REGISTRY_IMAGE" --file "$DOCKER_FILE" .
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$DOCKER_TAG"
    - docker push "$CI_REGISTRY_IMAGE:$DOCKER_TAG"
    - docker push "$CI_REGISTRY_IMAGE:latest"

deploy:
  image: beardedio/git-tools
  variables:
    SSH_PRIVATE_KEY: "set-as-secret-variable"
  stage: deploy
  only:
    - master
  script: git-push git@github.com:beardedio/git-tools.git
